name: Test, Build, and Deploy | Modul 01 - Lab2.2 Senior Project
 
on:
  push:
    branches: [main]
 
jobs:
  test-build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [16.x]
 
    steps:
      - uses: actions/checkout@v2
      - name: Testing Build pre-Deploy
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
   
  deploy:
    needs: test-build
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [16.x]
   
    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            set -e
            eval "${ssh-agent -s}"
            ssh-add ~/.ssh/ssh-praktikan4

            echo "Update Node.js version"
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs

            echo "Cek folder project";
            if [ ! -d "${HOME}/senpro/492878/modul02/senpro-github-action/" ]; then
              echo "Repository belum di-clone. Cloning...";
              mkdir -p ~/senpro/492878/modul02;
              cd ~/senpro/492878/modul02;
              git clone "https://github.com/ThisIsYefta/senpro-github-action.git";
            else
              echo "Repository sudah ada. Pulling updates...";
              cd ~/senpro/492878/modul02/senpro-github-action;
              git restore .;
              git pull origin main || { echo "Gagal pull repository"; exit 1; }
            fi

            echo "Install Package dan Build Project";
            npm cache clean --force;
            npm install || { echo "Gagal install package"; exit 1; }
            npm run build || { echo "Gagal build project"; exit 1; }
          